---
  - hosts: public1
    name: Gather facts from dcos public agent and private agent
    tasks: []

  - hosts: private1
    name: Gather facts from dcos public agent and private agent
    tasks: []

  - hosts: data_agents
    name: Gather facts from dcos public agent and private agent
    tasks: []

  - hosts: localhost
    tasks:

    - name: generate json file and copy to the json directory to prepare installation
      template:
        src: stage/mapr-controller.j2
        dest: json/mapr-controller.json

    - name: generate main.yml playbook
      template:
        src: stage/main.j2
        dest: ./main.yml

    - name: generate restart-web.yml playbook
      template:
        src: stage/restart-web.j2
        dest: playbooks/restart-web.yml

    - name: generate topology scripts
      template:
        src: stage/topology.j2
        dest: files/topology.sh

    - name: Generate json file for datanodes
      template:
        src: stage/mapr-data.j2
        dest: json/mapr-{{ hostvars[item]['container_name'] }}.json
      with_items: "{{ groups['data_agents'] }}"

    - name: Generate spawn playbooks for data nodes 
      template:
        src: stage/spawn-data.j2
        dest: playbooks/spawn-{{ hostvars[item]['container_name'] }}.yml
      with_items: "{{ groups['data_agents'] }}"
