- name: Use Marathon to grow MapR data nodes
  hosts: localhost
  tasks:

  - name: Spawn the MapR data2 node
    command: dcos marathon app add mapr-data2.json

  - name: Spawn the MapR data3 node
    command: dcos marathon app add mapr-data3.json

  - name: Spawn the MapR data4 node
    command: dcos marathon app add mapr-data4.json
