- name: Install additional services in controller
  hosts: mapr
  tasks:

  - name: Install hbase-master
    yum:
      name: mapr-hbase-master
      state: present

  - name: Install hbase
    yum:
      name: mapr-hbase
      state: present

  - name: Install Drill
    yum:
      name: mapr-drill
      state: present
 
  - name: Install Jobtracker
    yum:
      name: mapr-jobtracker
      state: present

  - name: Reconfigure the services
    command: /opt/mapr/server/configure.sh -R
