- name: Use Marathon to create MapR cluster
  hosts: localhost
  tasks:

  - name: Spawn the MapR controller
    command: dcos marathon app add mapr-controller.json

  - pause:
      seconds: 180

  - name: Copy web.conf file to controller
    command: sshpass -p "mapr" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no web.conf root@9.0.2.130:/opt/mapr/conf/

- name: Install additional services in controller
  hosts: mapr
  tasks:

  - name: Install portmap
    yum:
      name: portmap
      state: present

  - name: Start rpcbind
    service:
      name: rpcbind
      state: started
      enabled: yes

  - name: Reconfigure the services
    command: /opt/mapr/server/configure.sh -R

  - name: Restart web server
    command: maprcli node services -nodes comc1 -webserver restart

- name: Use Marathon to create MapR data nodes
  hosts: localhost
  tasks:

  - name: Spawn the MapR data1 node
    command: dcos marathon app add mapr-data1.json

  - name: Spawn the MapR data2 node
    command: dcos marathon app add mapr-data2.json

  - name: Spawn the MapR data3 node
    command: dcos marathon app add mapr-data3.json

  - name: Spawn the MapR data4 node
    command: dcos marathon app add mapr-data4.json
