- name: Use Marathon to create MapR cluster
  hosts: localhost
  tasks:

  - name: Copy web.conf file to controller
    command: sshpass -p "mapr" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no web.conf root@9.0.1.130:/opt/mapr/conf/

- name: Restart web service
  hosts: mapr
  tasks:

  - name: Restart web server
    command: maprcli node services -nodes comc1 -webserver restart
