---
  - hosts: all
    tasks:

    - pause:
        seconds: 30

    - name: generate hosts file and copy to all the nodes in the cluster
      template:
        src: ../files/hosts.j2
        dest: /tmp/hosts
        owner: root

    - name: move the hosts file to the /etc directory
      command: cp /tmp/hosts /etc/hosts
