---
  - hosts: cluster
    tasks:

    - name: Install portmap
      yum:
        name: portmap
        state: present

    - name: Start rpcbind
      service:
        name: rpcbind
        state: started
        enabled: yes
